AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*.rb'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/TrailingCommaInArrayLiteral:
    EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
    EnforcedStyleForMultiline: consistent_comma
